logging:
    pattern:
        dateformat: MM-dd HH:mm:ss:SSS
spring:
    rabbitmq:
        host: 192.168.204.128 #rabbitMQ的ip地址
        port: 5672
        username: lemur
        password: 123456
        virtual-host: /
        listener:
          simple:
              prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息